export default [
  {
    engineer_id: "123",
    avatar: "1.jpg",
    userinfo: "Hanna Gover",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "100",
    address: "大阪府大阪市111111",
    name: "AAA歯科医院",
    namecard_consent_flag: "1",
    paid: "1",
    paid_day: "2023-01-12",
    created_at: "2023-01-02",
    division: "歯科医師",
    divisionstatus: "light-blue lighten-3",
  },
  {
    engineer_id: "452",
    avatar: "2.jpg",
    userinfo: "Daniel Kristeen",
    usermail: "hgover@gmail.com",
    affiliation_id: "456789",
    clinics_id: "345",
    address: "大阪府大阪市＊＊＊＊＊",
    name: "BBB歯科技工所",
    namecard_consent_flag: "1",
    paid: "1",
    paid_day: "2023-01-12",
    created_at: "2023-01-20",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
  {
    engineer_id: "565",
    avatar: "3.jpg",
    userinfo: "Julian Josephs",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "11234",
    address: "大阪府大阪市＊＊＊＊＊",
    name: "CCC歯科医院",
    namecard_consent_flag: "0",
    paid: "0",
    paid_day: "",
    created_at: "2023-01-23",
    division: "歯科衛生士",
    divisionstatus: "red lighten-4",
  },
  {
    engineer_id: "785",
    avatar: "4.jpg",
    userinfo: "Jan Petrovic",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "11234",
    address: "大阪府大阪市＊＊＊＊＊",
    name: "GGGラボラトリー",
    namecard_consent_flag: "1",
    paid: "2",
    paid_day: "2023-02-12",
    created_at: "2023-02-22",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
  {
    engineer_id: "564",
    avatar: "5.jpg",
    userinfo: "Leanne Graham",
    usermail: "hgover@gmail.com",
    affiliation_id: "56789",
    clinics_id: "1123",
    address: "大阪府大阪市＊＊＊＊＊",
    name: "あああああ",
    namecard_consent_flag: "1",
    paid: "0",
    paid_day: "",
    created_at: "2023-01-20",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
  {
    engineer_id: "980",
    avatar: "6.jpg",
    userinfo: "Mrs. Dennis Schulist",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "22231",
    address: "大阪府大阪市＊＊＊＊＊",
    name: "MMMM",
    namecard_consent_flag: "",
    paid: "",
    paid_day: "",
    created_at: "2023-01-20",
    division: "歯科医師",
    divisionstatus: "light-blue lighten-3",
  },
];
