export default [
  {
    engineer_id: "123",
    avatar: "1.jpg",
    userinfo: "Hanna Gover",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "1",
    labos_id: "",
    name: "AAA歯科医院",
    namecard_consent_flag: "1",
    jdate: "2023-01-02",
    division: "歯科医師",
    divisionstatus: "light-blue lighten-3",
  },
  {
    engineer_id: "452",
    avatar: "2.jpg",
    userinfo: "Daniel Kristeen",
    usermail: "hgover@gmail.com",
    affiliation_id: "456789",
    clinics_id: "",
    labos_id: "1",
    name: "BBB歯科技工所",
    namecard_consent_flag: "1",
    jdate: "2023-01-20",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
  {
    engineer_id: "565",
    avatar: "3.jpg",
    userinfo: "Julian Josephs",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "2",
    labos_id: "",
    name: "CCC歯科医院",
    namecard_consent_flag: "0",
    jdate: "2023-01-23",
    division: "歯科衛生士",
    divisionstatus: "red lighten-4",
  },
  {
    engineer_id: "785",
    avatar: "4.jpg",
    userinfo: "Jan Petrovic",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "",
    labos_id: "1",
    name: "GGGラボラトリー",
    namecard_consent_flag: "1",
    jdate: "2023-02-22",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
  {
    engineer_id: "564",
    avatar: "5.jpg",
    userinfo: "Leanne Graham",
    usermail: "hgover@gmail.com",
    affiliation_id: "56789",
    clinics_id: "",
    labos_id: "2",
    name: "あああああ",
    namecard_consent_flag: "1",
    jdate: "2023-01-20",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
  {
    engineer_id: "980",
    avatar: "6.jpg",
    userinfo: "Mrs. Dennis Schulist",
    usermail: "hgover@gmail.com",
    affiliation_id: "789",
    clinics_id: "2",
    labos_id: "",
    name: "MMMM",
    namecard_consent_flag: "",
    jdate: "2023-01-20",
    division: "歯科医師",
    divisionstatus: "light-blue lighten-3",
  },
  {
    engineer_id: "521",
    avatar: "7.jpg",
    userinfo: "Kurtis Weissnat",
    usermail: "hgover@gmail.com",
    affiliation_id: "456789",
    clinics_id: "2",
    labos_id: "",
    name: "YYY",
    namecard_consent_flag: "1",
    jdate: "2023-01-20",
    division: "歯科衛生士",
    divisionstatus: "red lighten-4",
  },
  {
    engineer_id: "450",
    avatar: "8.jpg",
    userinfo: "Nicholas Runolfsdottir V",
    usermail: "hgover@gmail.com",
    affiliation_id: "89",
    clinics_id: "2",
    labos_id: "",
    name: "",
    namecard_consent_flag: "0",
    jdate: "2023-01-20",
    division: "歯科衛生士",
    divisionstatus: "red lighten-4",
  },
  {
    engineer_id: "212",
    avatar: "2.jpg",
    userinfo: "Glenna Reichert",
    usermail: "hgover@gmail.com",
    affiliation_id: "9",
    clinics_id: "1",
    labos_id: "",
    name: "JJJ歯科医院",
    namecard_consent_flag: "1",
    jdate: "2023-01-20",
    division: "歯科衛生士",
    divisionstatus: "red lighten-4",
  },
  {
    engineer_id: "152",
    avatar: "1.jpg",
    userinfo: "Clementina DuBuque",
    usermail: "hgover@gmail.com",
    affiliation_id: "456789",
    clinics_id: "",
    labos_id: "2",
    name: "PPPPP Labo",
    namecard_consent_flag: "1",
    jdate: "2023-01-20",
    division: "歯科技工士",
    divisionstatus: "green lighten-3",
  },
];
