export default [
  {
    member_code: "#123",
    avatar: "1.jpg",
    userinfo: "中山太郎",
    usermail: "hgover@gmail.com",
    phone: "090-456-7890",
    address: "大阪府大阪市１−１−１",
    affiliation: "歯科技工所名称＊＊",
  },
  {
    member_code: "#452",
    avatar: "2.jpg",
    userinfo: "佐々木次郎",
    usermail: "hgover@gmail.com",
    phone: "234-456-1789",
    address: "東京都港区１−１−１",
    affiliation: "歯科医院ここに企業名",
  },
  {
    member_code: "#565012",
    avatar: "3.jpg",
    userinfo: "大森三郎",
    usermail: "hgover@gmail.com",
    phone: "+345 456 789",
    address: "大阪府堺市１−１−１",
    affiliation: "歯科技工ここに企業名",
  },
  {
    member_code: "#785",
    avatar: "4.jpg",
    userinfo: "Jan Petrovic",
    usermail: "hgover@gmail.com",
    phone: "+456 456 789",
    address: "大阪府大阪市中央区１−１−１",
    affiliation: "ここに企業名＊＊＊＊＊",
  },
  {
    member_code: "#564",
    avatar: "5.jpg",
    userinfo: "Leanne Graham",
    usermail: "hgover@gmail.com",
    phone: "+567 456 789",
    address: "東京都港区１２３−３３１",
    affiliation: "ここに企業名",
  },
  {
    member_code: "#980",
    avatar: "6.jpg",
    userinfo: "Mrs. Dennis Schulist",
    usermail: "hgover@gmail.com",
    phone: "+678 456 789",
    address: "東京都世田谷区１−１−１",
    affiliation: "デンタルオフィース＊＊",
  },
  {
    member_code: "#521",
    avatar: "7.jpg",
    userinfo: "Kurtis Weissnat",
    usermail: "hgover@gmail.com",
    phone: "+123 456 789",
    address: "東京都足立区１−１−１",
    affiliation: "ADD歯科技工所",
  },
  {
    member_code: "#450",
    avatar: "8.jpg",
    userinfo: "Nicholas Runolfsdottir V",
    usermail: "hgover@gmail.com",
    phone: "+234 456 789",
    address: "愛知県＊＊＊＊＊＊",
    affiliation: "＊＊＊＊＊＊大学病院",
  },
  {
    member_code: "#212",
    avatar: "2.jpg",
    userinfo: "Glenna Reichert",
    usermail: "hgover@gmail.com",
    phone: "+345 456 789",
    address: "兵庫県＊＊＊＊＊＊＊＊＊＊＊",
    affiliation: "AAAA歯科技工所",
  },
  {
    member_code: "#152",
    avatar: "1.jpg",
    userinfo: "Clementina DuBuque",
    usermail: "hgover@gmail.com",
    phone: "+456 456 789",
    address: "福岡県＊＊＊＊＊＊＊＊＊＊＊＊＊＊＊",
    affiliation: "****歯科医院",
  },
];
