export default [
  {
    name: "***さん（ログインしている登録者の氏名）",
    adress: "大阪府＊＊＊＊ログインしている登録者の住所",
    society_id: "#12",
    society_name: "日本歯科医療管理学会",
    society_class: "0:歯科医学会関連",
    society_member_code: "",
    approval: "0",
  },
  {
    name: "***さん",
    society_id: "#1512",
    society_name: "BBAAVVVVVVV学会",
    society_class: "0:歯科医学会関連",
    society_member_code: "1234",
    approval: "1",
  },
  {
    name: "***さん",
    society_id: "#152",
    society_name: "ACC学会",
    society_class: "2:歯科技工士関連",
    society_member_code: "3992",
    approval: "2",
  },
  {
    name: "***さん",
    society_id: "#152",
    society_name: "AAA学会",
    society_class: "1:歯科医師関連",
    society_member_code: "3467",
    approval: "1",
  },
  {
    name: "***さん",
    society_id: "#152",
    society_name: "AAddA学会",
    society_class: "3:歯科衛生士関連",
    society_member_code: "",
    approval: "0",
  },
  {
    name: "***さん",
    society_id: "#10052",
    society_name: "CCCAAA学会",
    society_class: "4:その他",
    society_member_code: "",
    approval: "0",
  },
];
