export default [
  {
    id: "#123",
    avatar: "1.jpg",
    userinfo: "Hanna Gover",
    usermail: "hgover@gmail.com",
    phone: "090-456-7890",
    jdate: "2014-12-01",
    role: "歯科技工士",
    rolestatus: "cyan lighten-3",
  },
  {
    id: "#452",
    avatar: "2.jpg",
    userinfo: "Daniel Kristeen",
    usermail: "hgover@gmail.com",
    phone: "234-456-1789",
    jdate: "2019-08-01",
    role: "歯科技工士・チームリーダー",
    rolestatus: "light-blue lighten-3",
  },
  {
    id: "#565012",
    avatar: "3.jpg",
    userinfo: "Julian Josephs",
    usermail: "hgover@gmail.com",
    phone: "+345 456 789",
    jdate: "2011-09-09",
    role: "歯科技工士・CAD/CAM部門チームリーダー",
    rolestatus: "teal lighten-3",
  },
  {
    id: "#785",
    avatar: "4.jpg",
    userinfo: "Jan Petrovic",
    usermail: "hgover@gmail.com",
    phone: "+456 456 789",
    jdate: "2017-01-01",
    role: "Designer",
    rolestatus: "green lighten-3",
  },
  {
    id: "#564",
    avatar: "5.jpg",
    userinfo: "Leanne Graham",
    usermail: "hgover@gmail.com",
    phone: "+567 456 789",
    jdate: "2015-11-03",
    role: "HR",
    rolestatus: "deep-purple lighten-2",
  },
  {
    id: "#980",
    avatar: "6.jpg",
    userinfo: "Mrs. Dennis Schulist",
    usermail: "hgover@gmail.com",
    phone: "+678 456 789",
    jdate: "2013-03-12",
    role: "Designer",
    rolestatus: "indigo lighten-2",
  },
  {
    id: "#521",
    avatar: "7.jpg",
    userinfo: "Kurtis Weissnat",
    usermail: "hgover@gmail.com",
    phone: "+123 456 789",
    jdate: "05-10-2012",
    role: "Manager",
    rolestatus: "blue lighten-2",
  },
  {
    id: "#450",
    avatar: "8.jpg",
    userinfo: "Nicholas Runolfsdottir V",
    usermail: "hgover@gmail.com",
    phone: "+234 456 789",
    jdate: "2014-06-30",
    role: "Chairman",
    rolestatus: "red lighten-3",
  },
  {
    id: "#212",
    avatar: "2.jpg",
    userinfo: "Glenna Reichert",
    usermail: "hgover@gmail.com",
    phone: "+345 456 789",
    jdate: "2017-12-05",
    role: "Designer",
    rolestatus: "indigo lighten-4",
  },
  {
    id: "#152",
    avatar: "1.jpg",
    userinfo: "Clementina DuBuque",
    usermail: "hgover@gmail.com",
    phone: "+456 456 789",
    jdate: "2009-05-11",
    role: "Developer",
    rolestatus: "indigo lighten-4",
  },
];
