export default [
  {
    id: "#123",
    avatar: "1.jpg",
    name: "Hanna Gover",
    usermail: "hgover@gmail.com",
    egaocoin: "456",
    tsuraicoin: "54",
    created_at: "2014/12/1",
    role: "Designer",
    rolestatus: "cyan lighten-3",
  },
  {
    id: "#452",
    avatar: "2.jpg",
    name: "Daniel Kristeen",
    usermail: "hgover@gmail.com",
    egaocoin: "23",
    tsuraicoin: "54",
    created_at: "2014/12/2",
    role: "Developer",
    rolestatus: "light-blue lighten-3",
  },
  {
    id: "#565",
    avatar: "3.jpg",
    name: "Julian Josephs",
    usermail: "hgover@gmail.com",
    egaocoin: "789",
    tsuraicoin: "540",
    created_at: "2014/12/3",
    role: "Accountant",
    rolestatus: "teal lighten-3",
  },
  {
    id: "#785",
    avatar: "4.jpg",
    name: "Jan Petrovic",
    usermail: "hgover@gmail.com",
    egaocoin: "9",
    tsuraicoin: "154",
    created_at: "2014/12/7",
    role: "Designer",
    rolestatus: "green lighten-3",
  },
  {
    id: "#564",
    avatar: "5.jpg",
    name: "Leanne Graham",
    usermail: "hgover@gmail.com",
    egaocoin: "89",
    tsuraicoin: "54",
    created_at: "2014/12/10",
    role: "HR",
    rolestatus: "deep-purple lighten-2",
  },
  {
    id: "#980",
    avatar: "6.jpg",
    name: "Mrs. Dennis Schulist",
    usermail: "hgover@gmail.com",
    egaocoin: "67",
    tsuraicoin: "54",
    created_at: "2014/12/1",
    role: "Designer",
    rolestatus: "indigo lighten-2",
  },
  {
    id: "#521",
    avatar: "7.jpg",
    name: "Kurtis Weissnat",
    usermail: "hgover@gmail.com",
    egaocoin: "+69",
    tsuraicoin: "54",
    created_at: "2014/12/1",
    role: "Manager",
    rolestatus: "blue lighten-2",
  },
  {
    id: "#450",
    avatar: "8.jpg",
    name: "Nicholas Runolfsdottir V",
    usermail: "hgover@gmail.com",
    egaocoin: "89",
    tsuraicoin: "54",
    created_at: "2014/12/1",
    role: "Chairman",
    rolestatus: "red lighten-3",
  },
  {
    id: "#212",
    avatar: "2.jpg",
    name: "Glenna Reichert",
    usermail: "hgover@gmail.com",
    egaocoin: "34",
    tsuraicoin: "54",
    created_at: "2014/12/1",
    role: "Designer",
    rolestatus: "indigo lighten-4",
  },
  {
    id: "#152",
    avatar: "1.jpg",
    name: "Clementina DuBuque",
    usermail: "hgover@gmail.com",
    egaocoin: "89",
    tsuraicoin: "54",
    created_at: "2014/12/1",
    role: "Developer",
    rolestatus: "indigo lighten-4",
  },
];
